name: Update ENIGMA-PD assessment terms JSON file

on:
  schedule:
    # Run once a week on Monday at 8 AM EST in winter, 9 AM EDT in summer
    - cron: '0 13 * * 1'
  workflow_dispatch:

jobs:
  update-terms:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a Neurobagel Bot token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.NB_BOT_ID }}
          private-key: ${{ secrets.NB_BOT_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: iss-15/auto-update-terms-file
          token: ${{ steps.generate-token.outputs.token }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          COMMUNITIES_GOOGLE_API_KEY: ${{ secrets.COMMUNITIES_GOOGLE_API_KEY}}
          ENIGMA_ASSESSMENTS_GSHEET_ID: ${{ vars.ENIGMA_ASSESSMENTS_GSHEET_ID }}
        run: python code/create_enigma_terms_json.py

      - name: Get Neurobagel Bot App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
    
      - name: Configure git for Neurobagel Bot user
        run: |
          git config --global user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Commit and push if terms file has changed
        run: |
          if ! git diff --quiet configs/ENIGMA-PD/*; then
            git add configs/ENIGMA-PD/*
            git commit -m "[bot] Update ENIGMA-PD assessment terms"
            git push origin iss-15/auto-update-terms-file
          fi
